services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bank-system
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # optional: SQL scripts run on first start
      # - ./db/init:/docker-entrypoint-initdb.d

volumes:
  pgdata: